language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-android-support

script:
- ./gradlew --stacktrace androidDependencies
- ./gradlew --stacktrace
- ls ./app/build/outputs/apk/app-debug.apk