sudo: required

language: java

services:
  - docker

before_install:
- docker pull d3trax/android-build
- docker run -v `pwd`:/project d3trax/android-build run_build

script:
- ls ./app/build/outputs/apk/app-debug.apk