language: bash

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

sudo: required

services:
  - docker

before_install:
- docker pull d3trax/android-fastlane
- docker run -v `pwd`:/project -v $HOME/.gradle:/root/.gradle d3trax/android-fastlane

script:
- ls ./app/build/outputs/apk/app-debug.apk